version: '3'

services:
  app:
    image: 'sd_backend'
    ports:
      - "8433:8433"
    container_name: app
    depends_on:
      - db

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/assigment
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=assigment
